package jdbcdemo.dao;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import domain.Person;
public class PersonRepository {
Connection connection;
String createTableSql = "CREATE TABLE person("
+ "id INT GENERATED BY DEFAULT AS IDENTITY,"
+ "name VARCHAR(20),"
+ "surname VARCHAR(50),"
+ "age INT"
+ ")";
String insertSql = "INSERT INTO person(name, surname, age) "
+ "VALUES(?,?,?)";
String selectAllSql = "SELECT * FROM person";
String selectByIdSql = "SELECT * FROM person WHERE id=?";
Statement createTable;
PreparedStatement insert;
PreparedStatement selectAll;
public PersonRepository(){
try {
connection =
DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");
createTable = connection.createStatement();
insert = connection.prepareStatement(insertSql);
selectAll = connection.prepareStatement(selectAllSql);
} catch (SQLException e) {
e.printStackTrace();
}
}
public List<Person> getAll(){
List<Person> result = new ArrayList<Person>();
try {
ResultSet rs = selectAll.executeQuery();
while(rs.next()){
Person p = new Person();
p.setId(rs.getInt("id"));
p.setAge(rs.getInt("age"));
p.setName(rs.getString("name"));
p.setSurname(rs.getString("surname"));
result.add(p);
}
} catch (SQLException e) {
e.printStackTrace();
}
return result;
}
public void add(Person p){
try {
insert.setString(1, p.getName());
insert.setString(2, p.getSurname());
insert.setInt(3, p.getAge());
insert.executeUpdate();
} catch (SQLException e) {
e.printStackTrace();
}
}
public void createTable(){
try {
createTable.executeUpdate(createTableSql);
} catch (SQLException e) {
e.printStackTrace();
}
}
}
